### ISSUE TITLE
React Group Project - Kanban Board Setup

### ISSUE THREAD

**Issue by asdt560** [asdt560/rocket-mission-list#25]
https://github.com/users/asdt560/projects/4

Our team contains 2 members.

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @asdt560 and @Camilovelag,

✔️ Kanban board is well set up and assigned accordingly

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
